from werkzeug.exceptions import HTTPException
from app.models.card import Card
import pytest


def test_delete_one_card(client):
    pass
